### ISSUE TITLE
Script fails if FB event location is empty

### ISSUE THREAD

**Issue by charles-hood** [berettavexee/events-scrapper#2]
Get this error on some events:
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: ._4dpf._phw

After some investigation, it appears this happens when the Facebook event does not include complete location information.
Some events, for location, instead of a name and address, it just has a link. This fails.

Could you put try/except code around this line so it adds a blank location to the calendar for that event, rather than exiting the script with a failure?

Maybe something like this:
            try:
              event_info["location"] = self.browser.find_element_by_class_name(
                  "_4dpf._phw").text
            except NoSuchElementException:
              event_info["location"] = "TBD"

Example events that trigger this failure:
https://www.facebook.com/events/1140886672933580/
https://www.facebook.com/events/594600484704371/

**Comment by berettavexee** [comment]
hello, charles, 

I updated the code this morning. It handles errors and missing information better. The absence of locations, description or summary no longer crashes the script.

Best regards
